-- M1 (PR-Review Agentic Workflows): persistence for the new PrWorkflow SPI.
--
-- A pr_workflow_run row records one invocation of a registered PrWorkflow
-- (initially only "review") for a specific bot + repository + PR number.
-- Steps are an append-only log of progress / errors per run; they are
-- intentionally simple so the orchestrator can persist them eagerly without
-- coupling to any particular workflow implementation.
--
-- Status taxonomy (kept as VARCHAR for forward compatibility):
--   QUEUED           -- created, not yet started
--   RUNNING          -- workflow.run() in progress
--   WAITING_DEPLOY   -- awaiting an external callback (introduced in M3)
--   SUCCESS          -- workflow.run() completed with status SUCCESS
--   FAILED           -- workflow.run() threw or returned FAILED
--   CANCELLED        -- superseded by a newer run for the same PR

CREATE TABLE IF NOT EXISTS pr_workflow_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_id BIGINT NOT NULL,
    repo_owner VARCHAR(255) NOT NULL,
    repo_name VARCHAR(255) NOT NULL,
    pr_number BIGINT NOT NULL,
    workflow_key VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    summary VARCHAR(2048),
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    CONSTRAINT fk_pr_workflow_run_bot
        FOREIGN KEY (bot_id) REFERENCES bots(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pr_workflow_run_pr
    ON pr_workflow_runs (repo_owner, repo_name, pr_number);

CREATE INDEX IF NOT EXISTS idx_pr_workflow_run_bot_status
    ON pr_workflow_runs (bot_id, status);

CREATE TABLE IF NOT EXISTS pr_workflow_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    step_order INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    log_excerpt CLOB,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_pr_workflow_step_run
        FOREIGN KEY (run_id) REFERENCES pr_workflow_runs(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pr_workflow_step_run
    ON pr_workflow_steps (run_id);

