-- M2 (PR-Review Agentic Workflows): reusable workflow configurations.
--
-- A workflow_configurations row is a named whitelist of PrWorkflow keys that
-- a bot may run on PR webhook events. Each row owns 0..n workflow_selections,
-- one per enabled PrWorkflow, with the workflow-specific params persisted as
-- normalised (name, value) rows in workflow_selection_params (validated
-- against PrWorkflow.paramsSchema() on save/read).
--
-- The "Default" configuration row, the built-in 'review' selection and the
-- one-time backfill of existing bots are seeded by the companion migration
-- V15__workflow_configurations_default.sql so the new mandatory association
-- does not break upgrades and no startup-time Java logic is required.

CREATE TABLE IF NOT EXISTS workflow_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    default_entry BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS workflow_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_configuration_id BIGINT NOT NULL,
    workflow_key VARCHAR(64) NOT NULL,
    params_json TEXT,
    CONSTRAINT uk_workflow_selection UNIQUE (workflow_configuration_id, workflow_key),
    CONSTRAINT fk_workflow_selection_configuration
        FOREIGN KEY (workflow_configuration_id) REFERENCES workflow_configurations(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_workflow_selection_configuration
    ON workflow_selections (workflow_configuration_id);

CREATE TABLE IF NOT EXISTS workflow_selection_params (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_selection_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    param_value TEXT,
    CONSTRAINT uk_workflow_selection_param UNIQUE (workflow_selection_id, name),
    CONSTRAINT fk_workflow_selection_param_selection
        FOREIGN KEY (workflow_selection_id) REFERENCES workflow_selections(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_workflow_selection_param_selection
    ON workflow_selection_params (workflow_selection_id);

ALTER TABLE bots ADD COLUMN IF NOT EXISTS workflow_configuration_id BIGINT;

ALTER TABLE bots
    ADD CONSTRAINT IF NOT EXISTS fk_bots_workflow_configuration
    FOREIGN KEY (workflow_configuration_id) REFERENCES workflow_configurations(id);

