-- M3 (PR-Review Agentic Workflows): deployment targets + per-run callback channel.
--
-- A deployment_targets row describes ONE way the bot can ask the external
-- world to provision a per-PR preview environment. Strategy implementations
-- (WEBHOOK, STATIC; MCP and CI_ACTION arrive in later milestones) read the
-- per-target configuration JSON (encrypted at rest by EncryptionService when
-- APP_ENCRYPTION_KEY is configured) and translate it into HTTP calls or URL
-- template expansion. The bot itself never performs the deployment.
--
-- A bot may reference at most one deployment_target; if the column is NULL,
-- workflows that need a preview environment (E2ETestWorkflow in M4) abort
-- with a clear PR comment instead of running blind.
--
-- pr_workflow_runs gains three new columns:
--   preview_url             – populated by the strategy/callback when the env is ready,
--                             surfaced in the dashboard and PR comments.
--   callback_secret         – random per-run secret used by HMAC verification on
--                             the inbound /api/workflow-callback endpoint. Stored
--                             as plain hex; signature replay protection lives at
--                             the application layer.
--   deployment_handle_json  – opaque-to-the-bot JSON returned by trigger() so
--                             poll()/teardown() on the same strategy can find
--                             its own state again across requests.
--
-- All additions are idempotent (IF NOT EXISTS guards) so the migration can be
-- re-applied safely.

CREATE TABLE IF NOT EXISTS deployment_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    strategy_type VARCHAR(32) NOT NULL,
    config_json TEXT NOT NULL,
    preview_url_template VARCHAR(1024),
    timeout_seconds INT NOT NULL DEFAULT 600,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE bots ADD COLUMN IF NOT EXISTS deployment_target_id BIGINT;

ALTER TABLE bots
    ADD CONSTRAINT IF NOT EXISTS fk_bots_deployment_target
    FOREIGN KEY (deployment_target_id) REFERENCES deployment_targets(id);

ALTER TABLE pr_workflow_runs ADD COLUMN IF NOT EXISTS preview_url VARCHAR(2048);
ALTER TABLE pr_workflow_runs ADD COLUMN IF NOT EXISTS callback_secret VARCHAR(128);
ALTER TABLE pr_workflow_runs ADD COLUMN IF NOT EXISTS deployment_handle_json TEXT;
