-- M4 (PR-Review Agentic Workflows): persistence for the E2E test workflow.
--
-- A pr_test_suites row groups every generated test case for one
-- E2ETestWorkflow run on one PR. The (run_id, pr_number, framework) tuple
-- is unique per run — re-running the workflow on a new commit creates a
-- fresh suite tied to the new run id rather than mutating the previous
-- one, so the dashboard history stays auditable.
--
-- pr_test_cases holds the individual generated test files plus their last
-- execution outcome. The full file content is stored inline (TEXT) so the
-- bot can re-run / regenerate without re-cloning anything; lifecycle
-- modes (`ephemeral` default, `offer-as-pr` / `promote-on-merge` /
-- `commit-to-pr` come in M7) decide whether the row survives PR close.
--
-- All additions are idempotent so the migration can be re-applied safely.

CREATE TABLE IF NOT EXISTS pr_test_suites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    pr_number BIGINT NOT NULL,
    framework VARCHAR(32) NOT NULL,
    source_tree_ref VARCHAR(255),
    lifecycle_mode VARCHAR(32) NOT NULL DEFAULT 'ephemeral',
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_pr_test_suites_run
        FOREIGN KEY (run_id) REFERENCES pr_workflow_runs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pr_test_suites_run_id ON pr_test_suites(run_id);
CREATE INDEX IF NOT EXISTS idx_pr_test_suites_pr_number ON pr_test_suites(pr_number);

CREATE TABLE IF NOT EXISTS pr_test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suite_id BIGINT NOT NULL,
    path VARCHAR(1024) NOT NULL,
    title VARCHAR(512),
    content CLOB NOT NULL,
    last_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    last_run_at TIMESTAMP,
    last_duration_ms BIGINT,
    last_log CLOB,
    CONSTRAINT fk_pr_test_cases_suite
        FOREIGN KEY (suite_id) REFERENCES pr_test_suites(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pr_test_cases_suite_id ON pr_test_cases(suite_id);
