-- Initial schema for AI Git Bot (H2)

CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_integrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    provider_type VARCHAR(255) NOT NULL,
    api_url VARCHAR(255) NOT NULL,
    api_key VARCHAR(255),
    api_version VARCHAR(255),
    model VARCHAR(255) NOT NULL,
    max_tokens INTEGER NOT NULL DEFAULT 4096,
    max_diff_chars_per_chunk INTEGER NOT NULL DEFAULT 120000,
    max_diff_chunks INTEGER NOT NULL DEFAULT 8,
    retry_truncated_chunk_chars INTEGER NOT NULL DEFAULT 60000,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS git_integrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    provider_type VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    username VARCHAR(255),
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS bots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    prompt CLOB,
    webhook_secret VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ai_integration_id BIGINT NOT NULL,
    git_integration_id BIGINT NOT NULL,
    agent_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    webhook_call_count BIGINT NOT NULL DEFAULT 0,
    ai_tokens_sent BIGINT NOT NULL DEFAULT 0,
    ai_tokens_received BIGINT NOT NULL DEFAULT 0,
    last_webhook_at TIMESTAMP,
    last_ai_call_at TIMESTAMP,
    last_error_message CLOB,
    last_error_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_bots_ai_integration FOREIGN KEY (ai_integration_id) REFERENCES ai_integrations(id),
    CONSTRAINT fk_bots_git_integration FOREIGN KEY (git_integration_id) REFERENCES git_integrations(id)
);
