-- V34: Tamper-evident audit trail for PR workflow and review actions.
-- Each run gets its own hash chain; genesis events have previous_hash=NULL.
-- Application code must only INSERT — never UPDATE or DELETE audit rows.

CREATE TABLE IF NOT EXISTS pr_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(64) NOT NULL,
    event_timestamp TIMESTAMP NOT NULL,
    hash CHAR(64) NOT NULL,
    previous_hash CHAR(64),
    bot_id BIGINT NOT NULL,
    repo_owner VARCHAR(255) NOT NULL,
    repo_name VARCHAR(255) NOT NULL,
    pr_number BIGINT NOT NULL,
    run_id BIGINT,
    step_index INTEGER,
    step_name VARCHAR(255),
    step_status VARCHAR(32),
    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(255),
    ai_session_id BIGINT,
    ai_usage_session_id VARCHAR(255),
    correlation_id VARCHAR(255),
    duration_ms BIGINT,
    input_tokens BIGINT,
    output_tokens BIGINT,
    event_payload_json TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_pr_audit_event_run
        FOREIGN KEY (run_id) REFERENCES pr_workflow_runs(id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_run ON pr_audit_events (run_id);
CREATE INDEX IF NOT EXISTS idx_audit_bot_repo_pr ON pr_audit_events (bot_id, repo_owner, repo_name, pr_number);
CREATE INDEX IF NOT EXISTS idx_audit_bot ON pr_audit_events (bot_id);
CREATE INDEX IF NOT EXISTS idx_audit_type ON pr_audit_events (event_type);
