CREATE TABLE IF NOT EXISTS review_sessions (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               created_at TIMESTAMP NOT NULL,
                                               pr_number BIGINT NOT NULL,
                                               prompt_name VARCHAR(255),
    repo_name VARCHAR(255) NOT NULL,
    repo_owner VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_review_sessions_repo_pr UNIQUE (repo_owner, repo_name, pr_number)
    );

CREATE TABLE IF NOT EXISTS agent_sessions (
                                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              branch_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    issue_number BIGINT NOT NULL,
    issue_title VARCHAR(255),
    pr_number BIGINT,
    repo_name VARCHAR(255) NOT NULL,
    repo_owner VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_agent_sessions_repo_issue UNIQUE (repo_owner, repo_name, issue_number),
    CONSTRAINT chk_agent_sessions_status CHECK (status IN ('IN_PROGRESS', 'PR_CREATED', 'UPDATING', 'COMPLETED', 'FAILED'))
    );

CREATE TABLE IF NOT EXISTS conversation_messages (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     content CLOB NOT NULL,
                                                     created_at TIMESTAMP NOT NULL,
                                                     role VARCHAR(255) NOT NULL,
    session_id BIGINT,
    agent_session_id BIGINT,
    CONSTRAINT fk_conversation_messages_session FOREIGN KEY (session_id) REFERENCES review_sessions(id),
    CONSTRAINT fk_conversation_messages_agent_session FOREIGN KEY (agent_session_id) REFERENCES agent_sessions(id)
    );

CREATE TABLE IF NOT EXISTS agent_file_changes (
                                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  commit_sha VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    operation VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    agent_session_id BIGINT,
    CONSTRAINT fk_agent_file_changes_agent_session FOREIGN KEY (agent_session_id) REFERENCES agent_sessions(id)
    );


create table IF NOT EXISTS  review_session_participants (
    session_id bigint not null,
    participant_login varchar(255) not null
);

alter table review_session_participants
    add constraint fk_review_session_participants_session
    foreign key (session_id) references review_sessions(id);

create index IF NOT EXISTS idx_review_session_participants_session_id
    on review_session_participants(session_id);
