ALTER TABLE git_integrations ADD COLUMN IF NOT EXISTS lock_version BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE git_integrations ADD COLUMN IF NOT EXISTS deletion_pending BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE git_integrations ADD COLUMN IF NOT EXISTS ssh_cleanup_verified BOOLEAN DEFAULT FALSE NOT NULL;
