-- Persist selected MCP tools per MCP configuration (whitelist for prompt exposure).

CREATE TABLE IF NOT EXISTS mcp_selected_tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mcp_configuration_id BIGINT NOT NULL,
    qualified_name VARCHAR(500) NOT NULL,
    server_name VARCHAR(255) NOT NULL,
    tool_name VARCHAR(255) NOT NULL,
    title VARCHAR(500),
    description TEXT,
    CONSTRAINT uk_mcp_selected_tool UNIQUE (mcp_configuration_id, qualified_name),
    CONSTRAINT fk_mcp_selected_tools_configuration
        FOREIGN KEY (mcp_configuration_id) REFERENCES mcp_configurations(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mcp_selected_tools_configuration
    ON mcp_selected_tools (mcp_configuration_id);

