-- Reusable per-bot whitelist of the built-in agent tools that may be exposed
-- to the AI. Analogous to mcp_configurations / mcp_selected_tools, but for
-- the in-process tools registered in org.remus.giteabot.agent.tools.ToolCatalog
-- (file, context, validation, writer-repository).
--
-- The bot foreign key (bots.bot_tool_configuration_id) and the data-migration
-- that backfills it to the default configuration are introduced in a
-- follow-up migration.

CREATE TABLE IF NOT EXISTS bot_tool_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    default_entry BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS bot_tool_selections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    configuration_id BIGINT NOT NULL,
    tool_name VARCHAR(255) NOT NULL,
    tool_kind VARCHAR(32)  NOT NULL,
    CONSTRAINT uk_bot_tool_selection UNIQUE (configuration_id, tool_name),
    CONSTRAINT fk_bot_tool_selection_configuration
        FOREIGN KEY (configuration_id) REFERENCES bot_tool_configurations(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bot_tool_selection_configuration
    ON bot_tool_selections (configuration_id);
