create table if not exists review_sessions
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone not null,
    pr_number   bigint                      not null,
    prompt_name varchar(255),
    repo_name   varchar(255)                not null,
    repo_owner  varchar(255)                not null,
    updated_at  timestamp(6) with time zone not null,
    constraint uk8g7hv90unpo5vdlu7atxj9cwt
        unique (repo_owner, repo_name, pr_number)
);

create table if not exists admin_users
(
    id            bigint generated by default as identity
        primary key,
    username      varchar(255) not null
        unique,
    password_hash varchar(255) not null,
    created_at    timestamp    not null,
    updated_at    timestamp    not null
);

create table if not exists ai_integrations
(
    id                          bigint generated by default as identity
        primary key,
    name                        varchar(255)           not null
        unique,
    provider_type               varchar(255)           not null,
    api_url                     varchar(255)           not null,
    api_key                     varchar(255),
    api_version                 varchar(255),
    model                       varchar(255)           not null,
    max_tokens                  integer default 4096   not null,
    max_diff_chars_per_chunk    integer default 120000 not null,
    max_diff_chunks             integer default 8      not null,
    retry_truncated_chunk_chars integer default 60000  not null,
    created_at                  timestamp              not null,
    updated_at                  timestamp              not null
);

create table if not exists git_integrations
(
    id            bigint generated by default as identity
        primary key,
    name          varchar(255) not null
        unique,
    provider_type varchar(255) not null,
    url           varchar(255) not null,
    username      varchar(255),
    token         varchar(255) not null,
    created_at    timestamp    not null,
    updated_at    timestamp    not null
);

create table if not exists bots
(
    id                 bigint generated by default as identity
        primary key,
    name               varchar(255)          not null
        unique,
    username           varchar(255)          not null,
    prompt             text,
    webhook_secret     varchar(255),
    enabled            boolean default true  not null,
    ai_integration_id  bigint                not null
        constraint fk_bots_ai_integration
            references ai_integrations,
    git_integration_id bigint                not null
        constraint fk_bots_git_integration
            references git_integrations,
    agent_enabled      boolean default false not null,
    webhook_call_count bigint  default 0     not null,
    ai_tokens_sent     bigint  default 0     not null,
    ai_tokens_received bigint  default 0     not null,
    last_webhook_at    timestamp,
    last_ai_call_at    timestamp,
    last_error_message text,
    last_error_at      timestamp,
    created_at         timestamp             not null,
    updated_at         timestamp             not null
);

create table if not exists agent_sessions
(
    id           bigint generated by default as identity
        primary key,
    branch_name  varchar(255),
    created_at   timestamp(6) with time zone not null,
    issue_number bigint                      not null,
    issue_title  varchar(255),
    pr_number    bigint,
    repo_name    varchar(255)                not null,
    repo_owner   varchar(255)                not null,
    status       varchar(255)                not null
        constraint agent_sessions_status_check
            check ((status)::text = ANY
        ((ARRAY ['IN_PROGRESS'::character varying, 'PR_CREATED'::character varying, 'UPDATING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])),
    updated_at   timestamp(6) with time zone not null,
    constraint ukdvx36yd4sv85abmfclnxyrufo
        unique (repo_owner, repo_name, issue_number)
);

create table if not exists conversation_messages
(
    id               bigint generated by default as identity
        primary key,
    content          text                        not null,
    created_at       timestamp(6) with time zone not null,
    role             varchar(255)                not null,
    session_id       bigint
        constraint fkg9qsctkavcvjfcr3imqmct5vy
            references review_sessions,
    agent_session_id bigint
        constraint fk9m0qyyfak1gpdogovx55owt02
            references agent_sessions
);

create table if not exists agent_file_changes
(
    id               bigint generated by default as identity
        primary key,
    commit_sha       varchar(255),
    created_at       timestamp(6) with time zone not null,
    operation        varchar(255)                not null,
    path             varchar(255)                not null,
    agent_session_id bigint
        constraint fkfej8x2bctwe4v3qsan22rgxva
            references agent_sessions
);


