-- Store reusable remote MCP configurations and allow one optional assignment per bot.

CREATE TABLE IF NOT EXISTS mcp_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    json_content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE bots ADD COLUMN IF NOT EXISTS mcp_configuration_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_bots_mcp_configuration'
          AND table_name = 'bots'
    ) THEN
        ALTER TABLE bots
            ADD CONSTRAINT fk_bots_mcp_configuration
            FOREIGN KEY (mcp_configuration_id) REFERENCES mcp_configurations(id);
    END IF;
END $$;
